# Generated by Django 5.2 on 2025-04-17 06:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('tender_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(verbose_name='Description')),
                ('attachment', models.CharField(verbose_name='Attachment')),
                ('max_duration', models.IntegerField(verbose_name='Max duration')),
                ('min_budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Min budget')),
                ('max_budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Max budget')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('deadline', models.DateField(verbose_name='Deadline')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
